# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 309d7b682a364e79c988a3d373602ed1bd52f9f178e0332db8d354c3426047112d819013b000ef3a118dbf1c2132c197c75fddc4e34c3bb985fcde2784ffa0c6

test:
  secret_key_base: 3956f021f47e43dd0fc0bd3a94905e41106e7c6f882280a1101a85e473aa68269cae7f97a6f9aa245afe58b6d806b0c387fd0f7091166ad5bc65a02f17f08055

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
